<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<KAF version="v1.eustagger" xml:lang="eu">
<text>
<wf wid="w1" sent="1">Jon</wf>
<wf wid="w2" sent="1">Arretxek</wf>
<wf wid="w3" sent="1">nobela</wf>
<wf wid="w4" sent="1">berri</wf>
<wf wid="w5" sent="1">bat</wf>
<wf wid="w6" sent="1">,</wf>
<wf wid="w7" sent="1">&quot;</wf>
<wf wid="w8" sent="1">Manila</wf>
<wf wid="w9" sent="1">konexioa</wf>
<wf wid="w10" sent="1">&quot;</wf>
<wf wid="w11" sent="1">izenburua</wf>
<wf wid="w12" sent="1">duena</wf>
<wf wid="w13" sent="1">,</wf>
<wf wid="w14" sent="1">aurkeztu</wf>
<wf wid="w15" sent="1">digu</wf>
<wf wid="w16" sent="1">.</wf>
<wf wid="w17" sent="2">Hasierako</wf>
<wf wid="w18" sent="2">planteamenduan</wf>
<wf wid="w19" sent="2">liburu</wf>
<wf wid="w20" sent="2">honek</wf>
<wf wid="w21" sent="2">Patricia</wf>
<wf wid="w22" sent="2">Highsmith-en</wf>
<wf wid="w23" sent="2">nobela</wf>
<wf wid="w24" sent="2">ezagun</wf>
<wf wid="w25" sent="2">baten</wf>
<wf wid="w26" sent="2">parodia</wf>
<wf wid="w27" sent="2">dirudi</wf>
<wf wid="w28" sent="2">.</wf>
<wf wid="w29" sent="3">Izan</wf>
<wf wid="w30" sent="3">ere</wf>
<wf wid="w31" sent="3">,</wf>
<wf wid="w32" sent="3">gaizkile</wf>
<wf wid="w33" sent="3">batzuek</wf>
<wf wid="w34" sent="3">emakume</wf>
<wf wid="w35" sent="3">aberats</wf>
<wf wid="w36" sent="3">baten</wf>
<wf wid="w37" sent="3">maskota</wf>
<wf wid="w38" sent="3">bahitu</wf>
<wf wid="w39" sent="3">dute</wf>
<wf wid="w40" sent="3">,</wf>
<wf wid="w41" sent="3">honen</wf>
<wf wid="w42" sent="3">truke</wf>
<wf wid="w43" sent="3">ordainsaria</wf>
<wf wid="w44" sent="3">eskatzeko</wf>
<wf wid="w45" sent="3">.</wf>
<wf wid="w46" sent="4">Emakumeak</wf>
<wf wid="w47" sent="4">ikertzaile</wf>
<wf wid="w48" sent="4">pribatu</wf>
<wf wid="w49" sent="4">bat</wf>
<wf wid="w50" sent="4">kontratatzea</wf>
<wf wid="w51" sent="4">erabakitzen</wf>
<wf wid="w52" sent="4">du</wf>
<wf wid="w53" sent="4">bahitzaileak</wf>
<wf wid="w54" sent="4">bilatzeko</wf>
<wf wid="w55" sent="4">.</wf>
<wf wid="w56" sent="5">Parodia</wf>
<wf wid="w57" sent="5">da</wf>
<wf wid="w58" sent="5">nobela</wf>
<wf wid="w59" sent="5">beltzen</wf>
<wf wid="w60" sent="5">parodia</wf>
<wf wid="w61" sent="5">,</wf>
<wf wid="w62" sent="5">adibidez</wf>
<wf wid="w63" sent="5">,</wf>
<wf wid="w64" sent="5">ikertzailea</wf>
<wf wid="w65" sent="5">eta</wf>
<wf wid="w66" sent="5">honen</wf>
<wf wid="w67" sent="5">laguntzailea</wf>
<wf wid="w68" sent="5">ez</wf>
<wf wid="w69" sent="5">baitira</wf>
<wf wid="w70" sent="5">,</wf>
<wf wid="w71" sent="5">egia</wf>
<wf wid="w72" sent="5">esan</wf>
<wf wid="w73" sent="5">,</wf>
<wf wid="w74" sent="5">oso</wf>
<wf wid="w75" sent="5">trebeak</wf>
<wf wid="w76" sent="5">,</wf>
<wf wid="w77" sent="5">eta</wf>
<wf wid="w78" sent="5">zeozertan</wf>
<wf wid="w79" sent="5">asmatzen</wf>
<wf wid="w80" sent="5">badute</wf>
<wf wid="w81" sent="5">,</wf>
<wf wid="w82" sent="5">kasualitate</wf>
<wf wid="w83" sent="5">hutsez</wf>
<wf wid="w84" sent="5">izango</wf>
<wf wid="w85" sent="5">da</wf>
<wf wid="w86" sent="5">.</wf>
<wf wid="w87" sent="6">Gauzak</wf>
<wf wid="w88" sent="6">honela</wf>
<wf wid="w89" sent="6">,</wf>
<wf wid="w90" sent="6">nobela</wf>
<wf wid="w91" sent="6">honetan</wf>
<wf wid="w92" sent="6">kontatzen</wf>
<wf wid="w93" sent="6">dena</wf>
<wf wid="w94" sent="6">marrazki</wf>
<wf wid="w95" sent="6">bizidunetatik</wf>
<wf wid="w96" sent="6">edota</wf>
<wf wid="w97" sent="6">komikietatik</wf>
<wf wid="w98" sent="6">hurbilago</wf>
<wf wid="w99" sent="6">dago</wf>
<wf wid="w100" sent="6">(</wf>
<wf wid="w101" sent="6">ikertzaileek</wf>
<wf wid="w102" sent="6">Mortadelo</wf>
<wf wid="w103" sent="6">eta</wf>
<wf wid="w104" sent="6">Filemonen</wf>
<wf wid="w105" sent="6">antza</wf>
<wf wid="w106" sent="6">handia</wf>
<wf wid="w107" sent="6">dute</wf>
<wf wid="w108" sent="6">)</wf>
<wf wid="w109" sent="6">beste</wf>
<wf wid="w110" sent="6">edozein</wf>
<wf wid="w111" sent="6">gauzatatik</wf>
<wf wid="w112" sent="6">baino</wf>
<wf wid="w113" sent="6">.</wf>
<wf wid="w114" sent="7">Edonola</wf>
<wf wid="w115" sent="7">ere</wf>
<wf wid="w116" sent="7">,</wf>
<wf wid="w117" sent="7">Jon</wf>
<wf wid="w118" sent="7">Arretxe</wf>
<wf wid="w119" sent="7">oso</wf>
<wf wid="w120" sent="7">idazle</wf>
<wf wid="w121" sent="7">trebea</wf>
<wf wid="w122" sent="7">da</wf>
<wf wid="w123" sent="7">honelako</wf>
<wf wid="w124" sent="7">istorioak</wf>
<wf wid="w125" sent="7">gauzatzeko</wf>
<wf wid="w126" sent="7">,</wf>
<wf wid="w127" sent="7">behin</wf>
<wf wid="w128" sent="7">baino</wf>
<wf wid="w129" sent="7">gehiagotan</wf>
<wf wid="w130" sent="7">erakutsi</wf>
<wf wid="w131" sent="7">duen</wf>
<wf wid="w132" sent="7">bezala</wf>
<wf wid="w133" sent="7">.</wf>
<wf wid="w134" sent="8">Kasu</wf>
<wf wid="w135" sent="8">honetan</wf>
<wf wid="w136" sent="8">ere</wf>
<wf wid="w137" sent="8">bere</wf>
<wf wid="w138" sent="8">irudimenak</wf>
<wf wid="w139" sent="8">ez</wf>
<wf wid="w140" sent="8">dio</wf>
<wf wid="w141" sent="8">hutsik</wf>
<wf wid="w142" sent="8">egin</wf>
<wf wid="w143" sent="8">eta</wf>
<wf wid="w144" sent="8">nobela</wf>
<wf wid="w145" sent="8">argumentu</wf>
<wf wid="w146" sent="8">korapilatsua</wf>
<wf wid="w147" sent="8">duena</wf>
<wf wid="w148" sent="8">,</wf>
<wf wid="w149" sent="8">egitea</wf>
<wf wid="w150" sent="8">lortu</wf>
<wf wid="w151" sent="8">du</wf>
<wf wid="w152" sent="8">.</wf>
<wf wid="w153" sent="9">Argumentuaren</wf>
<wf wid="w154" sent="9">tonua</wf>
<wf wid="w155" sent="9">,</wf>
<wf wid="w156" sent="9">bestaldetik</wf>
<wf wid="w157" sent="9">,</wf>
<wf wid="w158" sent="9">azken</wf>
<wf wid="w159" sent="9">aldean</wf>
<wf wid="w160" sent="9">pixka</wf>
<wf wid="w161" sent="9">bat</wf>
<wf wid="w162" sent="9">moteltzen</wf>
<wf wid="w163" sent="9">da</wf>
<wf wid="w164" sent="9">,</wf>
<wf wid="w165" sent="9">baina</wf>
<wf wid="w166" sent="9">literaturan</wf>
<wf wid="w167" sent="9">denbora-pasa</wf>
<wf wid="w168" sent="9">arina</wf>
<wf wid="w169" sent="9">bilatzen</wf>
<wf wid="w170" sent="9">duenak</wf>
<wf wid="w171" sent="9">badu</wf>
<wf wid="w172" sent="9">nora</wf>
<wf wid="w173" sent="9">jo</wf>
<wf wid="w174" sent="9">,</wf>
<wf wid="w175" sent="9">idazle</wf>
<wf wid="w176" sent="9">honen</wf>
<wf wid="w177" sent="9">zaleak</wf>
<wf wid="w178" sent="9">ez</wf>
<wf wid="w179" sent="9">baitira</wf>
<wf wid="w180" sent="9">dezepzionatuta</wf>
<wf wid="w181" sent="9">sentituko</wf>
<wf wid="w182" sent="9">.</wf>
</text>
<terms>
<!-- Jon Arretxek -->
<term tid="t1" type="entity" lemma="Jon_Arretxe" pos="R.IZE-IZB" case="ERG" netype="Pertsona">
<span>
<target id="w1"/>
<target id="w2"/>
</span>
</term>
<!-- nobela -->
<term tid="t2" type="open" lemma="nobela" pos="N.IZE-ARR">
<span>
<target id="w3"/>
</span>
</term>
<!-- berri -->
<term tid="t3" type="open" lemma="berri" pos="G.ADJ-ARR">
<span>
<target id="w4"/>
</span>
</term>
<!-- bat -->
<term tid="t4" type="close" lemma="bat" pos="D.DET-DZH" case="ABS">
<span>
<target id="w5"/>
</span>
</term>
<!-- Manila -->
<term tid="t5" type="entity" lemma="Manila" pos="R.IZE-LIB" netype="Tokia">
<span>
<target id="w8"/>
</span>
</term>
<!-- konexioa -->
<term tid="t6" type="open" lemma="konexio" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w9"/>
</span>
</term>
<!-- izenburua -->
<term tid="t7" type="open" lemma="izenburu" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w11"/>
</span>
</term>
<!-- duena -->
<term tid="t8" type="open" lemma="ukan" pos="V.ADT_IZEELI" case="ABS">
<span>
<target id="w12"/>
</span>
</term>
<!-- aurkeztu -->
<term tid="t9" type="open" lemma="aurkeztu" pos="V.ADI-SIN">
<span>
<target id="w14"/>
</span>
</term>
<!-- digu -->
<term tid="t10" type="open" lemma="*edun" pos="V.ADL">
<span>
<target id="w15"/>
</span>
</term>
<!-- Hasierako -->
<term tid="t11" type="open" lemma="hasiera" pos="N.IZE-ARR" case="GEL">
<span>
<target id="w17"/>
</span>
</term>
<!-- planteamenduan -->
<term tid="t12" type="open" lemma="planteamendu" pos="N.IZE-ARR" case="INE">
<span>
<target id="w18"/>
</span>
</term>
<!-- liburu -->
<term tid="t13" type="open" lemma="liburu" pos="N.IZE-ARR">
<span>
<target id="w19"/>
</span>
</term>
<!-- honek -->
<term tid="t14" type="close" lemma="hau" pos="D.DET-ERKARR" case="ERG">
<span>
<target id="w20"/>
</span>
</term>
<!-- Patricia Highsmith-en -->
<term tid="t15" type="entity" lemma="Patricia_Highsmith" pos="R.IZE-IZB" case="GEN" netype="Pertsona">
<span>
<target id="w21"/>
<target id="w22"/>
</span>
</term>
<!-- nobela -->
<term tid="t16" type="open" lemma="nobela" pos="N.IZE-ARR">
<span>
<target id="w23"/>
</span>
</term>
<!-- ezagun -->
<term tid="t17" type="open" lemma="ezagun" pos="G.ADJ-ARR">
<span>
<target id="w24"/>
</span>
</term>
<!-- baten -->
<term tid="t18" type="close" lemma="bat" pos="D.DET-DZH" case="GEN">
<span>
<target id="w25"/>
</span>
</term>
<!-- parodia -->
<term tid="t19" type="open" lemma="parodia" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w26"/>
</span>
</term>
<!-- dirudi -->
<term tid="t20" type="open" lemma="iruditu" pos="V.ADT">
<span>
<target id="w27"/>
</span>
</term>
<!-- Izan ere -->
<term tid="t21" type="close" lemma="izan_ere" pos="C.LOT-LOK">
<span>
<target id="w29"/>
<target id="w30"/>
</span>
</term>
<!-- gaizkile -->
<term tid="t22" type="open" lemma="gaizkile" pos="N.IZE-ARR">
<span>
<target id="w32"/>
</span>
</term>
<!-- batzuek -->
<term tid="t23" type="close" lemma="batzuk" pos="D.DET-DZG" case="ERG">
<span>
<target id="w33"/>
</span>
</term>
<!-- emakume -->
<term tid="t24" type="open" lemma="emakume" pos="N.IZE-ARR">
<span>
<target id="w34"/>
</span>
</term>
<!-- aberats -->
<term tid="t25" type="open" lemma="aberats" pos="G.ADJ-ARR">
<span>
<target id="w35"/>
</span>
</term>
<!-- baten -->
<term tid="t26" type="close" lemma="bat" pos="D.DET-DZH" case="GEN">
<span>
<target id="w36"/>
</span>
</term>
<!-- maskota -->
<term tid="t27" type="open" lemma="maskota" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w37"/>
</span>
</term>
<!-- bahitu -->
<term tid="t28" type="open" lemma="bahitu" pos="V.ADI-SIN">
<span>
<target id="w38"/>
</span>
</term>
<!-- dute -->
<term tid="t29" type="open" lemma="*edun" pos="V.ADL">
<span>
<target id="w39"/>
</span>
</term>
<!-- honen -->
<term tid="t30" type="close" lemma="hau" pos="D.DET-ERKARR" case="GEN">
<span>
<target id="w41"/>
</span>
</term>
<!-- truke -->
<term tid="t31" type="open" lemma="truke" pos="N.IZE-ARR">
<span>
<target id="w42"/>
</span>
</term>
<!-- ordainsaria -->
<term tid="t32" type="open" lemma="ordainsari" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w43"/>
</span>
</term>
<!-- eskatzeko -->
<term tid="t33" type="open" lemma="eskatu" pos="V.ADI-SIN" case="ABS">
<span>
<target id="w44"/>
</span>
</term>
<!-- Emakumeak -->
<term tid="t34" type="open" lemma="emakume" pos="N.IZE-ARR" case="ERG">
<span>
<target id="w46"/>
</span>
</term>
<!-- ikertzaile -->
<term tid="t35" type="open" lemma="ikertzaile" pos="N.IZE-ARR">
<span>
<target id="w47"/>
</span>
</term>
<!-- pribatu -->
<term tid="t36" type="open" lemma="pribatu" pos="G.ADJ-ARR">
<span>
<target id="w48"/>
</span>
</term>
<!-- bat -->
<term tid="t37" type="close" lemma="bat" pos="D.DET-DZH" case="ABS">
<span>
<target id="w49"/>
</span>
</term>
<!-- kontratatzea -->
<term tid="t38" type="open" lemma="kontratatu" pos="V.ADI-SIN" case="ABS">
<span>
<target id="w50"/>
</span>
</term>
<!-- erabakitzen -->
<term tid="t39" type="open" lemma="erabaki" pos="V.ADI-SIN">
<span>
<target id="w51"/>
</span>
</term>
<!-- du -->
<term tid="t40" type="open" lemma="*edun" pos="V.ADL">
<span>
<target id="w52"/>
</span>
</term>
<!-- bahitzaileak -->
<term tid="t41" type="open" lemma="bahitzaile" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w53"/>
</span>
</term>
<!-- bilatzeko -->
<term tid="t42" type="open" lemma="bilatu" pos="V.ADI-SIN" case="ABS">
<span>
<target id="w54"/>
</span>
</term>
<!-- Parodia -->
<term tid="t43" type="open" lemma="parodia" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w56"/>
</span>
</term>
<!-- da -->
<term tid="t44" type="open" lemma="izan" pos="V.ADT">
<span>
<target id="w57"/>
</span>
</term>
<!-- nobela beltzen -->
<term tid="t45" type="open" lemma="nobela_beltz" pos="N.IZE-ARR" case="GEN">
<span>
<target id="w58"/>
<target id="w59"/>
</span>
</term>
<!-- parodia -->
<term tid="t46" type="open" lemma="parodia" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w60"/>
</span>
</term>
<!-- adibidez -->
<term tid="t47" type="open" lemma="adibidez" pos="A.ADB-ARR">
<span>
<target id="w62"/>
</span>
</term>
<!-- ikertzailea -->
<term tid="t48" type="open" lemma="ikertzaile" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w64"/>
</span>
</term>
<!-- eta -->
<term tid="t49" type="close" lemma="eta" pos="C.LOT-JNT">
<span>
<target id="w65"/>
</span>
</term>
<!-- honen -->
<term tid="t50" type="close" lemma="hau" pos="D.DET-ERKARR" case="GEN">
<span>
<target id="w66"/>
</span>
</term>
<!-- laguntzailea -->
<term tid="t51" type="open" lemma="laguntzaile" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w67"/>
</span>
</term>
<!-- ez -->
<term tid="t52" type="close" lemma="ez" pos="O.PRT">
<span>
<target id="w68"/>
</span>
</term>
<!-- baitira -->
<term tid="t53" type="open" lemma="izan" pos="V.ADT">
<span>
<target id="w69"/>
</span>
</term>
<!-- egia -->
<term tid="t54" type="open" lemma="egia" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w71"/>
</span>
</term>
<!-- esan -->
<term tid="t55" type="open" lemma="esan" pos="V.ADI-SIN">
<span>
<target id="w72"/>
</span>
</term>
<!-- oso -->
<term tid="t56" type="open" lemma="oso" pos="A.ADB-ARR">
<span>
<target id="w74"/>
</span>
</term>
<!-- trebeak -->
<term tid="t57" type="open" lemma="trebe" pos="G.ADJ-ARR" case="ABS">
<span>
<target id="w75"/>
</span>
</term>
<!-- eta -->
<term tid="t58" type="close" lemma="eta" pos="C.LOT-JNT">
<span>
<target id="w77"/>
</span>
</term>
<!-- zeozertan -->
<term tid="t59" type="close" lemma="zer_edo_zer" pos="O.IOR-IZGMGB" case="INE">
<span>
<target id="w78"/>
</span>
</term>
<!-- asmatzen -->
<term tid="t60" type="open" lemma="asmatu" pos="V.ADI-SIN">
<span>
<target id="w79"/>
</span>
</term>
<!-- badute -->
<term tid="t61" type="open" lemma="*edun" pos="V.ADL">
<span>
<target id="w80"/>
</span>
</term>
<!-- kasualitate -->
<term tid="t62" type="open" lemma="kasualitate" pos="N.IZE-ARR">
<span>
<target id="w82"/>
</span>
</term>
<!-- hutsez -->
<term tid="t63" type="open" lemma="huts" pos="G.ADJ-ARR" case="INS">
<span>
<target id="w83"/>
</span>
</term>
<!-- izango -->
<term tid="t64" type="open" lemma="izan" pos="V.ADI-SIN">
<span>
<target id="w84"/>
</span>
</term>
<!-- da -->
<term tid="t65" type="open" lemma="izan" pos="V.ADL">
<span>
<target id="w85"/>
</span>
</term>
<!-- Gauzak -->
<term tid="t66" type="open" lemma="gauza" pos="N.IZE-ARR" case="ERG">
<span>
<target id="w87"/>
</span>
</term>
<!-- honela -->
<term tid="t67" type="open" lemma="honela" pos="A.ADB-ARR">
<span>
<target id="w88"/>
</span>
</term>
<!-- nobela -->
<term tid="t68" type="open" lemma="nobela" pos="N.IZE-ARR">
<span>
<target id="w90"/>
</span>
</term>
<!-- honetan -->
<term tid="t69" type="close" lemma="hau" pos="D.DET-ERKARR" case="INE">
<span>
<target id="w91"/>
</span>
</term>
<!-- kontatzen -->
<term tid="t70" type="open" lemma="kontatu" pos="V.ADI-SIN">
<span>
<target id="w92"/>
</span>
</term>
<!-- dena -->
<term tid="t71" type="open" lemma="izan" pos="V.ADL_IZEELI" case="ABS">
<span>
<target id="w93"/>
</span>
</term>
<!-- marrazki bizidunetatik -->
<term tid="t72" type="open" lemma="marrazki_bizidun" pos="N.IZE-ARR" case="ABL">
<span>
<target id="w94"/>
<target id="w95"/>
</span>
</term>
<!-- edota -->
<term tid="t73" type="close" lemma="edota" pos="C.LOT-JNT">
<span>
<target id="w96"/>
</span>
</term>
<!-- komikietatik -->
<term tid="t74" type="open" lemma="komiki" pos="N.IZE-ARR" case="ABL">
<span>
<target id="w97"/>
</span>
</term>
<!-- hurbilago -->
<term tid="t75" type="open" lemma="hurbil" pos="G.ADJ-ARR" case="ABS">
<span>
<target id="w98"/>
</span>
</term>
<!-- dago -->
<term tid="t76" type="open" lemma="egon" pos="V.ADT">
<span>
<target id="w99"/>
</span>
</term>
<!-- ikertzaileek -->
<term tid="t77" type="open" lemma="ikertzaile" pos="N.IZE-ARR" case="ERG">
<span>
<target id="w101"/>
</span>
</term>
<!-- Mortadelo -->
<term tid="t78" type="entity" lemma="Mortadelo" pos="R.IZE-IZB" netype="Pertsona">
<span>
<target id="w102"/>
</span>
</term>
<!-- eta -->
<term tid="t79" type="close" lemma="eta" pos="C.LOT-JNT">
<span>
<target id="w103"/>
</span>
</term>
<!-- Filemonen -->
<term tid="t80" type="entity" lemma="Filemon" pos="R.IZE-IZB" case="GEN" netype="Pertsona">
<span>
<target id="w104"/>
</span>
</term>
<!-- antza -->
<term tid="t81" type="open" lemma="antza" pos="A.ADB-ARR">
<span>
<target id="w105"/>
</span>
</term>
<!-- handia -->
<term tid="t82" type="open" lemma="handi" pos="G.ADJ-ARR" case="ABS">
<span>
<target id="w106"/>
</span>
</term>
<!-- dute -->
<term tid="t83" type="open" lemma="ukan" pos="V.ADT">
<span>
<target id="w107"/>
</span>
</term>
<!-- beste -->
<term tid="t84" type="close" lemma="beste" pos="D.DET-DZG">
<span>
<target id="w109"/>
</span>
</term>
<!-- edozein -->
<term tid="t85" type="close" lemma="edozein" pos="D.DET-NOLARR">
<span>
<target id="w110"/>
</span>
</term>
<!-- gauzatatik -->
<term tid="t86" type="open" lemma="gauza" pos="N.IZE-ARR" case="ABL">
<span>
<target id="w111"/>
</span>
</term>
<!-- baino -->
<term tid="t87" type="close" lemma="baino" pos="O.BST">
<span>
<target id="w112"/>
</span>
</term>
<!-- Edonola -->
<term tid="t88" type="open" lemma="edonola" pos="A.ADB-ARR">
<span>
<target id="w114"/>
</span>
</term>
<!-- ere -->
<term tid="t89" type="close" lemma="ere" pos="C.LOT-LOK">
<span>
<target id="w115"/>
</span>
</term>
<!-- Jon Arretxe -->
<term tid="t90" type="entity" lemma="Jon_Arretxe" pos="R.IZE-IZB" case="ABS" netype="Pertsona">
<span>
<target id="w117"/>
<target id="w118"/>
</span>
</term>
<!-- oso -->
<term tid="t91" type="open" lemma="oso" pos="A.ADB-ARR">
<span>
<target id="w119"/>
</span>
</term>
<!-- idazle -->
<term tid="t92" type="open" lemma="idazle" pos="N.IZE-ARR">
<span>
<target id="w120"/>
</span>
</term>
<!-- trebea -->
<term tid="t93" type="open" lemma="trebe" pos="G.ADJ-ARR" case="ABS">
<span>
<target id="w121"/>
</span>
</term>
<!-- da -->
<term tid="t94" type="open" lemma="izan" pos="V.ADT">
<span>
<target id="w122"/>
</span>
</term>
<!-- honelako -->
<term tid="t95" type="open" lemma="honelako" pos="G.ADJ-ARR">
<span>
<target id="w123"/>
</span>
</term>
<!-- istorioak -->
<term tid="t96" type="open" lemma="istorio" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w124"/>
</span>
</term>
<!-- gauzatzeko -->
<term tid="t97" type="open" lemma="gauzatu" pos="V.ADI-SIN" case="ABS">
<span>
<target id="w125"/>
</span>
</term>
<!-- behin -->
<term tid="t98" type="open" lemma="behin" pos="A.ADB-ARR">
<span>
<target id="w127"/>
</span>
</term>
<!-- baino -->
<term tid="t99" type="close" lemma="baino" pos="O.BST">
<span>
<target id="w128"/>
</span>
</term>
<!-- gehiagotan -->
<term tid="t100" type="close" lemma="gehiago" pos="D.DET-DZG" case="INE">
<span>
<target id="w129"/>
</span>
</term>
<!-- erakutsi -->
<term tid="t101" type="open" lemma="erakutsi" pos="V.ADI-SIN">
<span>
<target id="w130"/>
</span>
</term>
<!-- duen -->
<term tid="t102" type="open" lemma="*edun" pos="V.ADL">
<span>
<target id="w131"/>
</span>
</term>
<!-- bezala -->
<term tid="t103" type="open" lemma="bezala" pos="A.ADB-ARR">
<span>
<target id="w132"/>
</span>
</term>
<!-- Kasu -->
<term tid="t104" type="open" lemma="kasu" pos="N.IZE-ARR">
<span>
<target id="w134"/>
</span>
</term>
<!-- honetan -->
<term tid="t105" type="close" lemma="hau" pos="D.DET-ERKARR" case="INE">
<span>
<target id="w135"/>
</span>
</term>
<!-- ere -->
<term tid="t106" type="close" lemma="ere" pos="C.LOT-LOK">
<span>
<target id="w136"/>
</span>
</term>
<!-- bere -->
<term tid="t107" type="close" lemma="bera" pos="D.DET-ERKIND" case="GEN">
<span>
<target id="w137"/>
</span>
</term>
<!-- irudimenak -->
<term tid="t108" type="open" lemma="irudimen" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w138"/>
</span>
</term>
<!-- ez -->
<term tid="t109" type="close" lemma="ez" pos="O.PRT">
<span>
<target id="w139"/>
</span>
</term>
<!-- dio -->
<term tid="t110" type="open" lemma="*edun" pos="V.ADL">
<span>
<target id="w140"/>
</span>
</term>
<!-- hutsik -->
<term tid="t111" type="open" lemma="huts" pos="N.IZE-ARR" case="PAR">
<span>
<target id="w141"/>
</span>
</term>
<!-- egin -->
<term tid="t112" type="open" lemma="egin" pos="V.ADI-SIN">
<span>
<target id="w142"/>
</span>
</term>
<!-- eta -->
<term tid="t113" type="close" lemma="eta" pos="C.LOT-JNT">
<span>
<target id="w143"/>
</span>
</term>
<!-- nobela -->
<term tid="t114" type="open" lemma="nobela" pos="N.IZE-ARR">
<span>
<target id="w144"/>
</span>
</term>
<!-- argumentu -->
<term tid="t115" type="open" lemma="argumentu" pos="N.IZE-ARR">
<span>
<target id="w145"/>
</span>
</term>
<!-- korapilatsua -->
<term tid="t116" type="open" lemma="korapilatsu" pos="G.ADJ-ARR" case="ABS">
<span>
<target id="w146"/>
</span>
</term>
<!-- duena -->
<term tid="t117" type="open" lemma="ukan" pos="V.ADT_IZEELI" case="ABS">
<span>
<target id="w147"/>
</span>
</term>
<!-- egitea -->
<term tid="t118" type="open" lemma="egin" pos="V.ADI-SIN" case="ABS">
<span>
<target id="w149"/>
</span>
</term>
<!-- lortu -->
<term tid="t119" type="open" lemma="lortu" pos="V.ADI-SIN">
<span>
<target id="w150"/>
</span>
</term>
<!-- du -->
<term tid="t120" type="open" lemma="*edun" pos="V.ADL">
<span>
<target id="w151"/>
</span>
</term>
<!-- Argumentuaren -->
<term tid="t121" type="open" lemma="argumentu" pos="N.IZE-ARR" case="GEN">
<span>
<target id="w153"/>
</span>
</term>
<!-- tonua -->
<term tid="t122" type="open" lemma="tonu" pos="N.IZE-ARR" case="ABS">
<span>
<target id="w154"/>
</span>
</term>
<!-- bestaldetik -->
<term tid="t123" type="open" lemma="bestalde" pos="N.IZE-ARR" case="ABL">
<span>
<target id="w156"/>
</span>
</term>
<!-- azken -->
<term tid="t124" type="close" lemma="azken" pos="D.DET-ORD">
<span>
<target id="w158"/>
</span>
</term>
<!-- aldean -->
<term tid="t125" type="open" lemma="alde" pos="N.IZE-ARR" case="INE">
<span>
<target id="w159"/>
</span>
</term>
<!-- pixka bat -->
<term tid="t126" type="close" lemma="pixka_bat" pos="D.DET-DZG" case="ABS">
<span>
<target id="w160"/>
<target id="w161"/>
</span>
</term>
<!-- moteltzen -->
<term tid="t127" type="open" lemma="moteldu" pos="V.ADI-SIN">
<span>
<target id="w162"/>
</span>
</term>
<!-- da -->
<term tid="t128" type="open" lemma="izan" pos="V.ADL">
<span>
<target id="w163"/>
</span>
</term>
<!-- baina -->
<term tid="t129" type="close" lemma="baina" pos="C.LOT-JNT">
<span>
<target id="w165"/>
</span>
</term>
<!-- literaturan -->
<term tid="t130" type="open" lemma="literatura" pos="N.IZE-ARR" case="INE">
<span>
<target id="w166"/>
</span>
</term>
<!-- denbora-pasa -->
<term tid="t131" type="open" lemma="denbora-pasa" pos="N.IZE-ARR">
<span>
<target id="w167"/>
</span>
</term>
<!-- arina -->
<term tid="t132" type="open" lemma="arin" pos="G.ADJ-ARR" case="ABS">
<span>
<target id="w168"/>
</span>
</term>
<!-- bilatzen -->
<term tid="t133" type="open" lemma="bilatu" pos="V.ADI-SIN">
<span>
<target id="w169"/>
</span>
</term>
<!-- duenak -->
<term tid="t134" type="open" lemma="*edun" pos="V.ADL_IZEELI" case="ABS">
<span>
<target id="w170"/>
</span>
</term>
<!-- badu -->
<term tid="t135" type="open" lemma="ukan" pos="V.ADT">
<span>
<target id="w171"/>
</span>
</term>
<!-- nora -->
<term tid="t136" type="open" lemma="nora" pos="A.ADB-GAL">
<span>
<target id="w172"/>
</span>
</term>
<!-- jo -->
<term tid="t137" type="open" lemma="jo" pos="V.ADI-SIN">
<span>
<target id="w173"/>
</span>
</term>
<!-- idazle -->
<term tid="t138" type="open" lemma="idazle" pos="N.IZE-ARR">
<span>
<target id="w175"/>
</span>
</term>
<!-- honen -->
<term tid="t139" type="close" lemma="hau" pos="D.DET-ERKARR" case="GEN">
<span>
<target id="w176"/>
</span>
</term>
<!-- zaleak -->
<term tid="t140" type="open" lemma="zale" pos="G.ADJ-ARR" case="ABS">
<span>
<target id="w177"/>
</span>
</term>
<!-- ez -->
<term tid="t141" type="close" lemma="ez" pos="O.PRT">
<span>
<target id="w178"/>
</span>
</term>
<!-- baitira -->
<term tid="t142" type="open" lemma="izan" pos="V.ADT">
<span>
<target id="w179"/>
</span>
</term>
<!-- dezepzionatuta -->
<term tid="t143" type="open" lemma="dezepzionatu" pos="V.ADI-SIN">
<span>
<target id="w180"/>
</span>
</term>
<!-- sentituko -->
<term tid="t144" type="open" lemma="sentitu" pos="V.ADI-SIN">
<span>
<target id="w181"/>
</span>
</term>
</terms>
<deps>
<!-- auxmod(asmatzen, badute) -->
<dep from="t60" to ="t61" rfunc="auxmod" />
<!-- auxmod(aurkeztu, digu) -->
<dep from="t9" to ="t10" rfunc="auxmod" />
<!-- auxmod(bahitu, dute) -->
<dep from="t28" to ="t29" rfunc="auxmod" />
<!-- auxmod(erabakitzen, du) -->
<dep from="t39" to ="t40" rfunc="auxmod" />
<!-- auxmod(izango, da) -->
<dep from="t64" to ="t65" rfunc="auxmod" />
<!-- auxmod(lortu, du) -->
<dep from="t119" to ="t120" rfunc="auxmod" />
<!-- auxmod(moteltzen, da) -->
<dep from="t127" to ="t128" rfunc="auxmod" />
<!-- cmod(jo, badu) -->
<dep from="t137" to ="t135" rfunc="cmod" />
<!-- detmod(Kasu, honetan) -->
<dep from="t104" to ="t105" rfunc="detmod" />
<!-- detmod(aldean, azken) -->
<dep from="t125" to ="t124" rfunc="detmod" />
<!-- detmod(gaizkile, batzuek) -->
<dep from="t22" to ="t23" rfunc="detmod" />
<!-- detmod(gauzatatik, edozein) -->
<dep from="t86" to ="t85" rfunc="detmod" />
<!-- detmod(ikertzaile, bat) -->
<dep from="t35" to ="t37" rfunc="detmod" />
<!-- detmod(liburu, honek) -->
<dep from="t13" to ="t14" rfunc="detmod" />
<!-- detmod(nobela, bat) -->
<dep from="t2" to ="t4" rfunc="detmod" />
<!-- detmod(nobela, honetan) -->
<dep from="t68" to ="t69" rfunc="detmod" />
<!-- ncmod(bahitu, emakume) -->
<dep from="t28" to ="t24" rfunc="ncmod" />
<!-- ncmod(baitira, adibidez) -->
<dep from="t53" to ="t47" rfunc="ncmod" />
<!-- ncmod(baitira, idazle) -->
<dep from="t142" to ="t138" rfunc="ncmod" />
<!-- ncmod(bilatzen, literaturan) -->
<dep from="t133" to ="t130" rfunc="ncmod" />
<!-- ncmod(da, Edonola) -->
<dep from="t94" to ="t88" rfunc="ncmod" />
<!-- ncmod(da, Jon_Arretxe) -->
<dep from="t94" to ="t90" rfunc="ncmod" />
<!-- ncmod(da, oso) -->
<dep from="t94" to ="t91" rfunc="ncmod" />
<!-- ncmod(dago, komikietatik) -->
<dep from="t76" to ="t74" rfunc="ncmod" />
<!-- ncmod(dago, marrazki_bizidunetatik) -->
<dep from="t76" to ="t72" rfunc="ncmod" />
<!-- ncmod(denbora-pasa, arina) -->
<dep from="t131" to ="t132" rfunc="ncmod" />
<!-- ncmod(dirudi, planteamenduan) -->
<dep from="t20" to ="t12" rfunc="ncmod" />
<!-- ncmod(dute, antza) -->
<dep from="t83" to ="t81" rfunc="ncmod" />
<!-- ncmod(dute, gauzatatik) -->
<dep from="t83" to ="t86" rfunc="ncmod" />
<!-- ncmod(egin, Kasu) -->
<dep from="t112" to ="t104" rfunc="ncmod" />
<!-- ncmod(emakume, aberats) -->
<dep from="t24" to ="t25" rfunc="ncmod" />
<!-- ncmod(erakutsi, bezala) -->
<dep from="t101" to ="t103" rfunc="ncmod" />
<!-- ncmod(esan, kasualitate) -->
<dep from="t55" to ="t62" rfunc="ncmod" />
<!-- ncmod(ikertzaile, pribatu) -->
<dep from="t35" to ="t36" rfunc="ncmod" />
<!-- ncmod(jo, nora) -->
<dep from="t137" to ="t136" rfunc="ncmod" />
<!-- ncmod(kasualitate, zeozertan) -->
<dep from="t62" to ="t59" rfunc="ncmod" />
<!-- ncmod(konexioa, Manila) -->
<dep from="t6" to ="t5" rfunc="ncmod" />
<!-- ncmod(kontatzen, nobela) -->
<dep from="t70" to ="t68" rfunc="ncmod" />
<!-- ncmod(moteltzen, aldean) -->
<dep from="t127" to ="t125" rfunc="ncmod" />
<!-- ncmod(nobela, Patricia_Highsmith-en) -->
<dep from="t16" to ="t15" rfunc="ncmod" />
<!-- ncmod(nobela, berri) -->
<dep from="t2" to ="t3" rfunc="ncmod" />
<!-- ncmod(nobela, ezagun) -->
<dep from="t16" to ="t17" rfunc="ncmod" />
<!-- ncmod(parodia, nobela_beltzen) -->
<dep from="t46" to ="t45" rfunc="ncmod" />
<!-- ncmod(planteamenduan, Hasierako) -->
<dep from="t12" to ="t11" rfunc="ncmod" />
<!-- ncmod(tonua, Argumentuaren) -->
<dep from="t122" to ="t121" rfunc="ncmod" />
<!-- ncmod(tonua, bestaldetik) -->
<dep from="t122" to ="t123" rfunc="ncmod" />
<!-- ncmod(truke, honen) -->
<dep from="t31" to ="t30" rfunc="ncmod" />
<!-- ncobj(bahitu, maskota) -->
<dep from="t28" to ="t27" rfunc="ncobj" case="ABS" />
<!-- ncobj(bilatzeko, bahitzaileak) -->
<dep from="t42" to ="t41" rfunc="ncobj" case="ABS" />
<!-- ncobj(bilatzen, denbora-pasa) -->
<dep from="t133" to ="t131" rfunc="ncobj" case="ABS" />
<!-- ncobj(dirudi, parodia) -->
<dep from="t20" to ="t19" rfunc="ncobj" case="ABS" />
<!-- ncobj(egin, hutsik) -->
<dep from="t112" to ="t111" rfunc="ncobj" case="PAR" />
<!-- ncobj(egin, irudimenak) -->
<dep from="t112" to ="t108" rfunc="ncobj" case="ABS" />
<!-- ncobj(esan, egia) -->
<dep from="t55" to ="t54" rfunc="ncobj" case="ABS" />
<!-- ncobj(kontratatzea, ikertzaile) -->
<dep from="t38" to ="t35" rfunc="ncobj" case="ABS" />
<!-- ncpred(da, Parodia) -->
<dep from="t44" to ="t43" rfunc="ncpred" />
<!-- ncpred(dago, hurbilago) -->
<dep from="t76" to ="t75" rfunc="ncpred" />
<!-- ncsubj(aurkeztu, Jon_Arretxek) -->
<dep from="t9" to ="t1" rfunc="ncsubj" case="ERG" />
<!-- ncsubj(bahitu, gaizkile) -->
<dep from="t28" to ="t22" rfunc="ncsubj" case="ERG" />
<!-- ncsubj(dirudi, liburu) -->
<dep from="t20" to ="t13" rfunc="ncsubj" case="ERG" />
<!-- ncsubj(kontatzen, Gauzak) -->
<dep from="t70" to ="t66" rfunc="ncsubj" case="ERG" />
<!-- ncsubj(kontratatzea, Emakumeak) -->
<dep from="t38" to ="t34" rfunc="ncsubj" case="ERG" />
<!-- xmod(bahitu, eskatzeko) -->
<dep from="t28" to ="t33" rfunc="xmod" case="ABS" />
<!-- xmod(erabakitzen, bilatzeko) -->
<dep from="t39" to ="t42" rfunc="xmod" case="ABS" />
</deps>
<chunks>
<!-- Jon Arretxek -->
<chunk cid="c1" head="t1" phrase="NP" case="ERG">
<span>
<target id="t1"/>
</span>
</chunk>
<!-- nobela berri bat -->
<chunk cid="c2" head="t2" phrase="NP" case="ABS">
<span>
<target id="t2"/>
<target id="t3"/>
<target id="t4"/>
</span>
</chunk>
<!-- Manila konexioa -->
<chunk cid="c3" head="t6" phrase="NP" case="ABS">
<span>
<target id="t5"/>
<target id="t6"/>
</span>
</chunk>
<!-- izenburua -->
<chunk cid="c4" head="t7" phrase="NP" case="ABS">
<span>
<target id="t7"/>
</span>
</chunk>
<!-- duena -->
<chunk cid="c5" head="t8" phrase="NP" case="ABS">
<span>
<target id="t8"/>
</span>
</chunk>
<!-- aurkeztu digu -->
<chunk cid="c6" head="t9" phrase="VP">
<span>
<target id="t9"/>
<target id="t10"/>
</span>
</chunk>
<!-- Hasierako planteamenduan -->
<chunk cid="c7" head="t12" phrase="NP" case="INE">
<span>
<target id="t11"/>
<target id="t12"/>
</span>
</chunk>
<!-- liburu honek -->
<chunk cid="c8" head="t13" phrase="NP" case="ERG">
<span>
<target id="t13"/>
<target id="t14"/>
</span>
</chunk>
<!-- baten parodia -->
<chunk cid="c9" head="t19" phrase="NP" case="ABS">
<span>
<target id="t18"/>
<target id="t19"/>
</span>
</chunk>
<!-- dirudi -->
<chunk cid="c10" head="t20" phrase="VP">
<span>
<target id="t20"/>
</span>
</chunk>
<!-- gaizkile batzuek -->
<chunk cid="c11" head="t22" phrase="NP" case="ERG">
<span>
<target id="t22"/>
<target id="t23"/>
</span>
</chunk>
<!-- baten maskota -->
<chunk cid="c12" head="t27" phrase="NP" case="ABS">
<span>
<target id="t26"/>
<target id="t27"/>
</span>
</chunk>
<!-- bahitu dute -->
<chunk cid="c13" head="t28" phrase="VP">
<span>
<target id="t28"/>
<target id="t29"/>
</span>
</chunk>
<!-- honen truke ordainsaria -->
<chunk cid="c14" head="t32" phrase="NP" case="ABS">
<span>
<target id="t30"/>
<target id="t31"/>
<target id="t32"/>
</span>
</chunk>
<!-- eskatzeko -->
<chunk cid="c15" head="t33" phrase="VP" case="ABS">
<span>
<target id="t33"/>
</span>
</chunk>
<!-- Emakumeak -->
<chunk cid="c16" head="t34" phrase="NP" case="ERG">
<span>
<target id="t34"/>
</span>
</chunk>
<!-- ikertzaile pribatu bat -->
<chunk cid="c17" head="t35" phrase="NP" case="ABS">
<span>
<target id="t35"/>
<target id="t36"/>
<target id="t37"/>
</span>
</chunk>
<!-- kontratatzea -->
<chunk cid="c18" head="t38" phrase="VP" case="ABS">
<span>
<target id="t38"/>
</span>
</chunk>
<!-- erabakitzen du -->
<chunk cid="c19" head="t39" phrase="VP">
<span>
<target id="t39"/>
<target id="t40"/>
</span>
</chunk>
<!-- bahitzaileak -->
<chunk cid="c20" head="t41" phrase="NP" case="ABS">
<span>
<target id="t41"/>
</span>
</chunk>
<!-- bilatzeko -->
<chunk cid="c21" head="t42" phrase="VP" case="ABS">
<span>
<target id="t42"/>
</span>
</chunk>
<!-- Parodia -->
<chunk cid="c22" head="t43" phrase="NP" case="ABS">
<span>
<target id="t43"/>
</span>
</chunk>
<!-- da -->
<chunk cid="c23" head="t44" phrase="VP">
<span>
<target id="t44"/>
</span>
</chunk>
<!-- nobela beltzen parodia -->
<chunk cid="c24" head="t46" phrase="NP" case="ABS">
<span>
<target id="t45"/>
<target id="t46"/>
</span>
</chunk>
<!-- adibidez -->
<chunk cid="c25" head="t47" phrase="NP">
<span>
<target id="t47"/>
</span>
</chunk>
<!-- ikertzailea -->
<chunk cid="c26" head="t48" phrase="NP" case="ABS">
<span>
<target id="t48"/>
</span>
</chunk>
<!-- honen laguntzailea -->
<chunk cid="c27" head="t51" phrase="NP" case="ABS">
<span>
<target id="t50"/>
<target id="t51"/>
</span>
</chunk>
<!-- egia -->
<chunk cid="c28" head="t54" phrase="NP" case="ABS">
<span>
<target id="t54"/>
</span>
</chunk>
<!-- esan -->
<chunk cid="c29" head="t55" phrase="VP">
<span>
<target id="t55"/>
</span>
</chunk>
<!-- oso trebeak -->
<chunk cid="c30" head="t57" phrase="NP" case="ABS">
<span>
<target id="t56"/>
<target id="t57"/>
</span>
</chunk>
<!-- zeozertan -->
<chunk cid="c31" head="t59" phrase="NP" case="INE">
<span>
<target id="t59"/>
</span>
</chunk>
<!-- asmatzen badute -->
<chunk cid="c32" head="t60" phrase="VP">
<span>
<target id="t60"/>
<target id="t61"/>
</span>
</chunk>
<!-- kasualitate hutsez -->
<chunk cid="c33" head="t62" phrase="NP" case="INS">
<span>
<target id="t62"/>
<target id="t63"/>
</span>
</chunk>
<!-- izango da -->
<chunk cid="c34" head="t64" phrase="VP">
<span>
<target id="t64"/>
<target id="t65"/>
</span>
</chunk>
<!-- Gauzak -->
<chunk cid="c35" head="t66" phrase="NP" case="ERG">
<span>
<target id="t66"/>
</span>
</chunk>
<!-- honela -->
<chunk cid="c36" head="t67" phrase="NP">
<span>
<target id="t67"/>
</span>
</chunk>
<!-- nobela honetan -->
<chunk cid="c37" head="t68" phrase="NP" case="INE">
<span>
<target id="t68"/>
<target id="t69"/>
</span>
</chunk>
<!-- marrazki bizidunetatik -->
<chunk cid="c38" head="t72" phrase="NP" case="ABL">
<span>
<target id="t72"/>
</span>
</chunk>
<!-- komikietatik -->
<chunk cid="c39" head="t74" phrase="NP" case="ABL">
<span>
<target id="t74"/>
</span>
</chunk>
<!-- hurbilago -->
<chunk cid="c40" head="t75" phrase="NP" case="ABS">
<span>
<target id="t75"/>
</span>
</chunk>
<!-- dago -->
<chunk cid="c41" head="t76" phrase="VP">
<span>
<target id="t76"/>
</span>
</chunk>
<!-- antza -->
<chunk cid="c42" head="t81" phrase="NP">
<span>
<target id="t81"/>
</span>
</chunk>
<!-- dute -->
<chunk cid="c43" head="t83" phrase="VP">
<span>
<target id="t83"/>
</span>
</chunk>
<!-- edozein gauzatatik -->
<chunk cid="c44" head="t86" phrase="NP" case="ABL">
<span>
<target id="t85"/>
<target id="t86"/>
</span>
</chunk>
<!-- Edonola -->
<chunk cid="c45" head="t88" phrase="NP">
<span>
<target id="t88"/>
</span>
</chunk>
<!-- Jon Arretxe -->
<chunk cid="c46" head="t90" phrase="NP" case="ABS">
<span>
<target id="t90"/>
</span>
</chunk>
<!-- oso idazle trebea -->
<chunk cid="c47" head="t92" phrase="NP" case="ABS">
<span>
<target id="t91"/>
<target id="t92"/>
<target id="t93"/>
</span>
</chunk>
<!-- da -->
<chunk cid="c48" head="t94" phrase="VP">
<span>
<target id="t94"/>
</span>
</chunk>
<!-- honelako istorioak -->
<chunk cid="c49" head="t96" phrase="NP" case="ABS">
<span>
<target id="t95"/>
<target id="t96"/>
</span>
</chunk>
<!-- gauzatzeko -->
<chunk cid="c50" head="t97" phrase="VP" case="ABS">
<span>
<target id="t97"/>
</span>
</chunk>
<!-- behin baino gehiagotan -->
<chunk cid="c51" head="t100" phrase="NP" case="INE">
<span>
<target id="t98"/>
<target id="t99"/>
<target id="t100"/>
</span>
</chunk>
<!-- erakutsi duen -->
<chunk cid="c52" head="t101" phrase="VP">
<span>
<target id="t101"/>
<target id="t102"/>
</span>
</chunk>
<!-- bezala -->
<chunk cid="c53" head="t103" phrase="NP">
<span>
<target id="t103"/>
</span>
</chunk>
<!-- Kasu honetan -->
<chunk cid="c54" head="t104" phrase="NP" case="INE">
<span>
<target id="t104"/>
<target id="t105"/>
</span>
</chunk>
<!-- bere irudimenak -->
<chunk cid="c55" head="t108" phrase="NP" case="ABS">
<span>
<target id="t107"/>
<target id="t108"/>
</span>
</chunk>
<!-- ez -->
<chunk cid="c56" head="t109" phrase="VP">
<span>
<target id="t109"/>
</span>
</chunk>
<!-- dio -->
<chunk cid="c57" head="t110" phrase="VP">
<span>
<target id="t110"/>
</span>
</chunk>
<!-- hutsik -->
<chunk cid="c58" head="t111" phrase="NP" case="PAR">
<span>
<target id="t111"/>
</span>
</chunk>
<!-- egin -->
<chunk cid="c59" head="t112" phrase="VP">
<span>
<target id="t112"/>
</span>
</chunk>
<!-- duena -->
<chunk cid="c60" head="t117" phrase="NP" case="ABS">
<span>
<target id="t117"/>
</span>
</chunk>
<!-- egitea -->
<chunk cid="c61" head="t118" phrase="VP" case="ABS">
<span>
<target id="t118"/>
</span>
</chunk>
<!-- lortu du -->
<chunk cid="c62" head="t119" phrase="VP">
<span>
<target id="t119"/>
<target id="t120"/>
</span>
</chunk>
<!-- Argumentuaren tonua -->
<chunk cid="c63" head="t122" phrase="NP" case="ABS">
<span>
<target id="t121"/>
<target id="t122"/>
</span>
</chunk>
<!-- bestaldetik -->
<chunk cid="c64" head="t123" phrase="NP" case="ABL">
<span>
<target id="t123"/>
</span>
</chunk>
<!-- azken aldean -->
<chunk cid="c65" head="t125" phrase="NP" case="INE">
<span>
<target id="t124"/>
<target id="t125"/>
</span>
</chunk>
<!-- pixka bat -->
<chunk cid="c66" head="t126" phrase="NP" case="ABS">
<span>
<target id="t126"/>
</span>
</chunk>
<!-- moteltzen da -->
<chunk cid="c67" head="t127" phrase="VP">
<span>
<target id="t127"/>
<target id="t128"/>
</span>
</chunk>
<!-- literaturan -->
<chunk cid="c68" head="t130" phrase="NP" case="INE">
<span>
<target id="t130"/>
</span>
</chunk>
<!-- denbora-pasa arina -->
<chunk cid="c69" head="t131" phrase="NP" case="ABS">
<span>
<target id="t131"/>
<target id="t132"/>
</span>
</chunk>
<!-- duenak -->
<chunk cid="c70" head="t134" phrase="NP" case="ABS">
<span>
<target id="t134"/>
</span>
</chunk>
<!-- badu -->
<chunk cid="c71" head="t135" phrase="VP">
<span>
<target id="t135"/>
</span>
</chunk>
<!-- nora -->
<chunk cid="c72" head="t136" phrase="NP">
<span>
<target id="t136"/>
</span>
</chunk>
<!-- jo -->
<chunk cid="c73" head="t137" phrase="VP">
<span>
<target id="t137"/>
</span>
</chunk>
<!-- idazle honen zaleak -->
<chunk cid="c74" head="t138" phrase="NP" case="ABS">
<span>
<target id="t138"/>
<target id="t139"/>
<target id="t140"/>
</span>
</chunk>
<!-- dezepzionatuta -->
<chunk cid="c75" head="t143" phrase="VP">
<span>
<target id="t143"/>
</span>
</chunk>
<!-- sentituko -->
<chunk cid="c76" head="t144" phrase="VP">
<span>
<target id="t144"/>
</span>
</chunk>
</chunks>
</KAF>
